import type { Metadata } from "next";
import { Playfair_Display, Work_Sans, Alegreya } from "next/font/google";
import "./globals.css";

const playfairDisplay = Playfair_Display({
  variable: "--font-primary",
  subsets: ["latin"],
});

const workSans = Work_Sans({
  variable: "--font-secondary",
  subsets: ["latin"],
});

const alegreya = Alegreya({
  variable: "--font-tertiary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfairDisplay.variable} ${workSans.variable} ${alegreya.variable}`}>
        {children}
      </body>
    </html>
  );
}
